French translation
AstarNetwork/astar-apps pull request #1096
Opened 2023-12-19 20:48 UTC by GuiGou12358

French translation

2023-12-20 03:22 UTC, impelcrypto approved these changes

2023-12-20 08:34 UTC, bobo-k2 requested changes
Thanks a lot for the PR. General comment, use single quotes instead ". I see a lot of errors, mostly code styling (linter) ones.
Run `yarn dev` to see errors.
Run `yarn lint --fix` to fix errors

2023-12-20 21:27 UTC, GuiGou12358 commented
@bobo-k2 
Indeed there was a lot of code styling issues.
It's fixed now :)

2023-12-27 11:09 UTC, bobo-k2 approved these changes
LGTM

2023-12-27 11:09 UTC, merged