Pink registration
AstarNetwork/astar-apps pull request #1127
Opened 2024-01-14 14:41 UTC by GuiGou12358

**Pull Request Summary**

Add `Pink `Asset. I will test the XCM transfers when the token will be available 

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**

Add `Pink `Asset

**Fixes**

- (ex: Fix validation function)

**Changes**

- (ex: Change document B)

**To-dos**

- [ ]  test XCM transfers when the token is available

2024-02-01 03:24 UTC, gluneau commented
Hello @GuiGou12358, please provide a publicly available preview URL, see https://docs.astar.network/docs/build/builder-guides/integration_toolings/deploy-astar-portal/#overview

2024-03-21 12:24 UTC, GuiGou12358 commented
Please find an available preview here: https://astar-portal-pink-asset-5qan80rdw-guigous-projects.vercel.app

2024-03-25 16:10 UTC, Kahonnohak approved these changes
LGTM

2024-03-26 12:39 UTC, Kahonnohak commented
@GuiGou12358 
Question - Is it possible to use the gas only DOT? Or prioritising DOT? This was my result (even I had both tokens in both chains)
- DOT token is used for gas fee when you bring PINK token to Astar
- USDT is used for gas fee when you send PINK token to AssetHub

2024-03-26 14:21 UTC, GuiGou12358 commented
@Kahonnohak 
Normaly, PINK token is used for gas fee when we bring PINK token to Astar
Curently, USDT is used for gas fee when we send PINK token to AssetHub. Here, from my understanding, we can use DOT token or any sufficient asset (USDT or USDC for example).

2024-03-27 06:58 UTC, impelcrypto requested changes

2024-03-29 09:30 UTC, GuiGou12358 commented on src/v2/repositories/implementations/XcmRepository.ts
> +      return { feeAssetIsRequired: true, feeAssetId: '4294969280', feeAmount: 700000 };
I did the changes

2024-03-29 09:31 UTC, GuiGou12358 commented
> @GuiGou12358 Thank you for your explanation.
> 
> > we can use DOT token or any sufficient asset (USDT or USDC for example).
> 
> Yes, I prefer to use DOT instead of USDT for fee. Could you update in this PR?

Sorry, I already did all that for free. Now I'd rather you take over.

2024-03-30 03:53 UTC, impelcrypto approved these changes

2024-03-30 03:54 UTC, merged