hotfix: merge the hotfix to main branch
AstarNetwork/astar-apps pull request #1135
Opened 2024-01-16 07:39 UTC by impelcrypto

**Pull Request Summary**

* hotfix: merge the hotfix to main branch
  * https://github.com/AstarNetwork/astar-apps/pull/1134 

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

2024-01-16 14:02 UTC, bobo-k2 approved these changes

2024-01-16 18:16 UTC, ayumitk approved these changes

2024-01-17 11:21 UTC, bobo-k2 requested changes
Lets wait until https://github.com/AstarNetwork/astar-apps/pull/1136 is merged, because merging this PR will delete `release-hotfix` branch

2024-01-17 14:47 UTC, impelcrypto commented
@bobo-k2 You can merge this PR anytime

2024-01-18 12:10 UTC, bobo-k2 approved these changes

2024-01-18 12:11 UTC, merged