Ledger support for unbond and withdraw
AstarNetwork/astar-apps pull request #1158
Opened 2024-01-29 15:36 UTC by bobo-k2

**Pull Request Summary**
Support for ledged users to unbond and withdraw their tokens. @Kahonnohak please update text.
<img width="703" alt="image" src="https://github.com/AstarNetwork/astar-apps/assets/8452361/c5b36cfb-d14f-4ad8-b7d2-b8c7921169ec">

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**

- (ex: Add feature A)

**Fixes**

- (ex: Fix validation function)

**Changes**

- (ex: Change document B)

**To-dos**

> \*Feel free to remove this section if it's not applicable

- [ ] (ex: add user list)

2024-01-29 16:51 UTC, impelcrypto requested changes

2024-01-29 16:51 UTC, impelcrypto commented on src/i18n/en-US/index.ts
> +    ledgerNotSupported: 'Ledger native accounts is not supported yet for dApp staking v3 yet.',
```suggestion
    ledgerNotSupported: 'Ledger native accounts are not supported for dApp staking V3 yet.',
```

2024-01-30 03:22 UTC, Kahonnohak commented
Hi @bobo-k2 for the UI message

- Lets mention EVM
- Add link to docs : https://docs.astar.network/docs/learn/dapp-staking/dapp-staking-faq/#q-i-am-a-leger-astar-native-app-user-what-do-i-need-to-do

How about message below (took same sentence from the docs) :
Your tokens are locked in dAppStaking V2. Please unbond and withdraw your tokens. dApp Staking V3 is temporally unavailable for those Ledger Astar Native App users, please move your funds to a soft wallet or a Ledger EVM account to be able to participate in dApp staking. (More information)

2024-01-30 08:20 UTC, bobo-k2 commented
> Hi @bobo-k2 for the UI message

Updated in https://github.com/AstarNetwork/astar-apps/pull/1158/commits/3b5d7db0896d37be8884281feb639eeac120b2ff

2024-01-30 09:36 UTC, impelcrypto approved these changes
LGTM, please check my comments

2024-01-30 09:36 UTC, impelcrypto commented on src/hooks/useAccount.ts
> +        message: 'Ledger is not supported on this network.',
Let's use i18 here

2024-01-30 09:36 UTC, impelcrypto commented on src/staking-v3/components/my-staking/MigrationSupport.vue
> +            href="https://docs.astar.network/docs/learn/dapp-staking/dapp-staking-faq/#q-i-am-a-leger-astar-native-app-user-what-do-i-need-to-do"
Let's import the url from `docsUrl` at `src/links.index`

2024-01-30 17:26 UTC, ayumitk approved these changes

2024-01-31 04:34 UTC, Kahonnohak approved these changes
LGTM!

2024-02-01 14:28 UTC, bobo-k2 commented
> LGTM, please check my comments

Thanks, a lot. The first think you commented was bug. I am not sure why I made that change. Fixed in https://github.com/AstarNetwork/astar-apps/pull/1158/commits/d6711a6a6492123890ca03f47ea473cd6234b419

2024-02-02 07:34 UTC, merged