Ledger dApp Staking V3 Promotion Card
AstarNetwork/astar-apps pull request #1304
Opened 2024-06-04 14:32 UTC by Gunit2481

**Pull Request Summary**

> Describe what changes this pull request makes to the repository
- Add Ledger dApp Staking V3 banner to `dapp_promotions` image folder;
- Update `dapp_promotions.json` file;

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**

- (ex: Add feature A)

**Fixes**

- (ex: Fix validation function)

**Changes**

- (ex: Change document B)

**To-dos**

> \*Feel free to remove this section if it's not applicable

- [ ] (ex: add user list)

2024-06-05 08:02 UTC, bobo-k2 requested changes

2024-06-05 08:02 UTC, bobo-k2 commented on src/data/dapp_promotions.json
> +    "name": "Ledger - dApp Staking V3",
Put the promotion info at the beginning of the file otherwise it won't be shown, because we are showing only first 5 promotions

2024-06-05 11:37 UTC, Gunit2481 reviewed
Fixed

2024-06-06 08:03 UTC, bobo-k2 approved these changes

2024-06-06 08:03 UTC, merged