Added localization config, French translation
AstarNetwork/astar-apps pull request #185
Opened 2021-12-06 08:00 UTC by Gunit2481

**Pull Request Summary**

-Added translation file for French

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes

**This pull request makes the following changes:**

**Adds**
- (ex: Add feature A)

**Fixes**
- (ex: Fix validation function)

**Changes**
- (ex: Change document B)

**To-dos**
- Feel free to remove this section if it's not applicable
- Probably add the language code into URL path

- [ ] (ex: add user list)

2021-12-06 08:30 UTC, hoonsubin commented on src/i18n/index.ts
> +import FR from './FR';
please use lower case

2021-12-06 10:08 UTC, Gunit2481 commented on src/i18n/index.ts
> +import FR from './FR';
Done !

2021-12-06 11:57 UTC, hoonsubin requested changes

2021-12-06 11:57 UTC, hoonsubin commented on src/i18n/index.ts
> +    code: 'FR',
Can you also make the code and the script name to use underscore?

2021-12-07 07:29 UTC, hoonsubin requested changes

2021-12-07 07:29 UTC, hoonsubin commented on src/i18n/index.ts
> +import fr from './fr';
You can still use `index.ts` for `fr/fr.ts`. The import name should be `fr` (like now)

2022-01-11 07:51 UTC, hoonsubin commented
The UI structure has changed a lot, I'm sorry to ask this, but can you close this PR and translate the page again? I will ensure it is mergable.
Thanks

2022-01-13 05:33 UTC, closed without merging