feat: integrate cBridge
AstarNetwork/astar-apps pull request #243
Opened 2022-02-01 19:13 UTC by impelcrypto

**Pull Request Summary**

* Added cBridge widget in /bridge/evm

![image](https://user-images.githubusercontent.com/92044428/152035095-8b3a9eac-03d5-4f14-afe0-f0a5cd9a6424.png)

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes

**This pull request makes the following changes:**

**Adds**
- (ex: Add feature A)

**Fixes**
- (ex: Fix validation function)

**Changes**
- (ex: Change document B)

**To-dos**
> *Feel free to remove this section if it's not applicable

- [ ] (ex: add user list)

2022-02-04 08:33 UTC, hoonsubin requested changes
There are a couple of UX-related issues.

1. If the bridge is only available on Astar, we should show the menu only when the user is connected to Astar. When I switch the `From` network to Shiden while being connected to Astar network in the portal, my MetaMask will request to switch networks while the portal is still on the same network. This feels very disjointed.
It would make more sense if the `From` network is the current network, but when the user selects a different network as `From`, the `To` network should be the current network. In other words, we don't want users to swap from Astar to Ethereum while being connected to Shiden.

![Screen Shot 2022-02-04 at 9 15 58 AM](https://user-images.githubusercontent.com/40356749/152496335-4935bdef-43f9-4827-a05f-169c8762acb3.png)

2. If the bridge is only usable with MetaMask, we should show the menu only when the user is connected with MetaMask.

![Screen Shot 2022-02-04 at 9 16 22 AM](https://user-images.githubusercontent.com/40356749/152496744-951cd20f-6248-4f29-8893-322bbaf7c767.png)

3. As a new user, it is confusing to understand how the rate works and what are bridge providers. For example, where can I get or buy AAVE coins, and can I really get 5000 ETH for 5000 ASTR tokens? I know this is just sending ERC20 tokens from one chain to another, but the first thing I see is the native tokens, not ERC20.
Maybe adding the token symbol at the end of the estimated value might help.

![Screen Shot 2022-02-04 at 9 21 26 AM](https://user-images.githubusercontent.com/40356749/152496882-86343f01-9c3a-49cc-84df-c8f8e44554b5.png)

2022-02-07 11:25 UTC, hoonsubin requested changes
https://user-images.githubusercontent.com/40356749/152779107-4d251a0b-6298-4198-aa1a-b12eca49cd6b.mov

Every time I select a different network, the page asks me to switch my network from MetaMask

2022-02-07 11:41 UTC, impelcrypto commented
@hoonsubin Yes, I thought MetaMask should always ask user to change the `networkId` to match with `source chain`

2022-02-07 11:43 UTC, hoonsubin commented
> @hoonsubin Yes, I thought MetaMask should always ask user to change the `networkId` to match with `source chain`

Yes, but I'm already connected to the same network

2022-02-07 11:52 UTC, impelcrypto commented
You have selected `Astar` as the source chain at 00:19 but the network in your MetaMask is `Ethereum Mainet` at 00:22 

![image](https://user-images.githubusercontent.com/92044428/152782938-1a5c6b8b-4340-43ae-9795-524b05f57f76.png)

![image](https://user-images.githubusercontent.com/92044428/152782850-48b4d2ae-2740-446a-ba47-0978d7272004.png)

2022-02-08 02:10 UTC, sirius651 approved these changes
LGTM

2022-02-08 05:36 UTC, bobo-k2 approved these changes
LGTM. Great work.

2022-02-08 10:51 UTC, hoonsubin requested changes
Found an issue:

https://user-images.githubusercontent.com/40356749/152972590-cc91eeb7-f1ce-4d14-a362-2286418fc1fa.mov

Connecting to Shiden and clicking the network switch button on the bridge from Shiden to Astar disconnects the wallet from the page

2022-02-08 14:24 UTC, impelcrypto commented
>Connecting to Shiden and clicking the network switch button on the bridge from Shiden to Astar disconnects the wallet from the page

@hoonsubin I just saw your comment. The portal has to `reload` the page whenever the network has been changed. I think I can't modify this behavior because the initial state for the destination chain is `Astar` and source chain is `Ethereum` whenever the portal selects `Astar network`.
 
https://github.com/AstarNetwork/astar-apps/blob/main/src/components/balance/modals/ModalNetwork.vue#L132
https://github.com/AstarNetwork/astar-apps/blob/8cc982f7f4f1242d3994e7975ec85a3362e11fd0/src/hooks/c-bridge/useCbridge.ts#L187

2022-02-08 14:44 UTC, hoonsubin commented
> @hoonsubin Perhaps do not change the portal network whenever clicking the reverse button regardless of whether the 'from' or 'to' network is Astar or Shiden? In that case, user can bridge from Astar EVM while the portal has selected Shiden network.

Will they be able to use the bridge in that case? Another problem I found was when the user selects from Shiden to Astar and clicks on the reverse button, the option will reset to Ethereum to Astar so the portal connection can change to Astar.

2022-02-08 14:52 UTC, impelcrypto commented
>Will they be able to use the bridge in that case?

Yes, no problem. MetaMask will ask user to change the network (by popup)

> when the user selects from Shiden to Astar and clicks on the reverse button, the option will reset to Ethereum to Astar so the portal connection can change to Astar.

Yes, actually I covered [it](https://github.com/AstarNetwork/astar-apps/pull/243#issuecomment-1032665513) here. That's because the page has reloaded, but I can fix this in [this](https://github.com/AstarNetwork/astar-apps/pull/243#issuecomment-1032682247) solution.

2022-02-08 17:15 UTC, impelcrypto commented
@hoonsubin Fixed.

2022-02-08 17:33 UTC, hoonsubin approved these changes
LGTM

We will merge this once the announcement has been made

2022-02-20 02:22 UTC, impelcrypto commented on src/config/web3/utils/transactions.ts
> +export const sendNativeTokenTransaction = async (
@sirius651 
FYI: I'd like to modify the function name here.

2022-02-28 22:06 UTC, hoonsubin commented
@impelcrypto please resolve the conflicts

2022-03-03 12:15 UTC, merged