Integration RPC tests
AstarNetwork/astar-apps pull request #465
Opened 2022-07-19 09:22 UTC by niklabh

**Pull Request Summary**

Added mocha test suite for rpc node. This PR aims to introduce a framework for testing rpc node with typescript tests. This will help us test collator end to end.

Steps:

Download astar collator binary from releases
Spawn a local test network using child_process
Run test suite against that that test network

**Check list**
- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**
- test suite

2022-07-25 07:33 UTC, impelcrypto approved these changes

2022-07-25 08:44 UTC, sirius651 approved these changes

2022-07-25 11:22 UTC, bobo-k2 requested changes

2022-07-25 11:22 UTC, bobo-k2 commented on rpc-tests/tests/test-rpc.js
> +        const hash = await transfer.signAndSend(alice, { nonce: -1 });
As we discussed a few days ago. You will get hash as soon as node accepts transaction, which doesn't necessarily means that transaction will pass. Transaction events need to be parsed in order to determine if transaction succeed or not.  ref. https://github.com/AstarNetwork/astar-apps/blob/9fc092904f056a56f9b76a67f481b12b20cf0b39/src/modules/extrinsic/utils/index.ts#L26

2022-07-29 10:21 UTC, bobo-k2 commented
@niklabh please update this PR after you merge https://github.com/AstarNetwork/Astar/pull/709

2022-08-04 07:59 UTC, niklabh commented
Updated

2022-08-04 12:32 UTC, bobo-k2 approved these changes
LGTM

2022-08-04 12:45 UTC, merged