Algem ads on dApp Staking UI implementation
AstarNetwork/astar-apps pull request #470
Opened 2022-07-20 12:17 UTC by sirius651

**Pull Request Summary**

> Describe what changes this pull request makes to the repository

**Check list**
- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

![screencapture-localhost-8080-2022-07-20-15_37_05](https://user-images.githubusercontent.com/1606820/179979641-7bfe2695-7476-46dc-85ff-57c68513de2a.png)

<img width="514" alt="스크린샷 2022-07-20 오후 3 38 37" src="https://user-images.githubusercontent.com/1606820/179979564-f9a4cbf7-282a-44a7-ad9a-ec00c0d53099.png">

2022-07-20 13:02 UTC, bobo-k2 commented
Header and footer are not aligned properly, at least on my machine (Chrome in mobile device mode) and phone

<img width="376" alt="image" src="https://user-images.githubusercontent.com/8452361/179988442-ecc49511-baf2-49d5-8340-242c6f2897ea.png">
<img width="381" alt="image" src="https://user-images.githubusercontent.com/8452361/179988507-a6773bed-d108-4f62-b843-b255841670f8.png">

2022-07-20 16:53 UTC, impelcrypto requested changes

2022-07-20 16:53 UTC, impelcrypto commented on src/components/dapp-staking/AlgemPanel.vue
> +<template>
Let's define texts in i18n file.

2022-07-21 02:47 UTC, Kahonnohak commented
Thanks! looking good:)

Please kindly take a look.

- The wallet drawer closes instead when I wanted to accept the term.
https://gyazo.com/491bbc2eedbb99328c93c2fb1984e061


Design side

** Tab **
- Status
-- Default (not selected) -> change the font weight to 500
-- Hover -> Change the font weight to 700
-- Focus (selected) -> have the blue line


-Styling
-- Please make the blue line round

-- The architecture is this : 
<img width="602" alt="Screenshot 2022-07-21 at 11 20 14" src="https://user-images.githubusercontent.com/77480847/180116056-2dee00f4-fbe9-4ad9-af54-c8d021716683.png">
--- please add 16px side padding
--- fix the width to 240 for this page (mobile 160px)
 
-- When changing the statuses, it's dancing. 
https://gyazo.com/17082dd1f5b4ef74259b3ca3222a0922

-- Animation: could we have the same animation when we hover transfer modal? (I couldn't find the code for that modal)


**Algem Ads**

- Please add a radius same as contents above - > .5rem

- Risk warning area
-- Could you please add a yellow underline when hovering, also make the icon yellow as default, please.  
-- Let's make the link icon smaller 32->24 and could you adjust the line height please?
<img width="703" alt="Screenshot 2022-07-21 at 11 36 33" src="https://user-images.githubusercontent.com/77480847/180118861-1fb972d7-3232-4139-a318-fd4f7b20a7ed.png">

- I can see the line here and the background image is repeating? prefer to use just image if there is no problem.
<img width="888" alt="Screenshot 2022-07-21 at 11 38 17" src="https://user-images.githubusercontent.com/77480847/180118878-67b15663-42b2-4f10-a79c-0a95d9214e74.png">



I have to go now but I would like to add a few adjustments on mobile as well. I'll come back for this in the afternoon.

2022-07-21 02:49 UTC, impelcrypto requested changes

2022-07-21 02:49 UTC, impelcrypto commented on src/components/dapp-staking/AlgemPanel.vue
> +    <a href="https://app.algem.io/liquid-staking" target="_blank">
`cursor: pointer` should not appear outside of the button.
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/92044428/180113510-4b2c6492-e992-46f9-9e50-c38b790fc96b.png">

2022-07-21 02:59 UTC, impelcrypto commented
Let's fix the styling for mobile devices.

![image](https://user-images.githubusercontent.com/92044428/180120300-604b8495-6b70-410b-9198-b35c128825bb.png)

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/92044428/180120384-6cb2ecb7-af39-431e-b4e7-c39f2a5d75f4.png">

2022-07-21 06:04 UTC, Kahonnohak commented
For the mobile:

This is the design - I think the design is not ready for mobile yet?
![Algem on dApp Staking V1 mobile](https://user-images.githubusercontent.com/77480847/180140913-a84eb881-0aae-4fde-8911-b569c2ea3f8c.png)

2022-07-21 08:22 UTC, sirius651 commented
<img width="217" alt="스크린샷 2022-07-21 오후 5 11 36" src="https://user-images.githubusercontent.com/1606820/180164319-655feb35-3ca6-4911-bf22-4bd54252d5c2.png">

Made a fix for mobile and feedbacks above. please take a look, and let me know if something missed. thanks 
@Kahonnohak @impelcrypto

2022-07-21 09:22 UTC, impelcrypto approved these changes

2022-07-21 12:39 UTC, Kahonnohak commented
Looking great!

Sorry I missed one thing - the image. We need to keep the ratio not shrink. You can place the image in the centre (sorry I placed it on the left) and fix the height 100% I think? so the width would be trimmed? I hope you got what I mean, otherwise I'll explain on the screen. 

With the risk warning - Sorry I didn't explain enough. 

- The link is the bottom one, not the top one. 
- see the image, with Figma I cannot change the colour of the underline but please keep the yellow for hovering. 
- And I would like the icon at the end of the sentence. And could you please make the icon grey again... it was a bit odd sorry!

<img width="776" alt="Screenshot 2022-07-21 at 21 24 22" src="https://user-images.githubusercontent.com/77480847/180215076-4cd15182-2413-4d0d-98f7-0489b63f270a.png">

2022-07-21 14:01 UTC, sirius651 commented
> Looking great!
> 
> Sorry I missed one thing - the image. We need to keep the ratio not shrink. You can place the image in the centre (sorry I placed it on the left) and fix the height 100% I think? so the width would be trimmed? I hope you got what I mean, otherwise I'll explain on the screen.
> 
> With the risk warning - Sorry I didn't explain enough.
> 
> * The link is the bottom one, not the top one.
> * see the image, with Figma I cannot change the colour of the underline but please keep the yellow for hovering.
> * And I would like the icon at the end of the sentence. And could you please make the icon grey again... it was a bit odd sorry!

I believe fixed what you mentioned, could you check again @Kahonnohak

2022-07-21 14:10 UTC, Kahonnohak commented
Awesome thanks! this looks good to me! I'll just share this with Shun before approving. Thanks!!

2022-07-25 07:18 UTC, Kahonnohak commented
@sirius651 

Thanks but I wanted to make the image fix on the left so the graphic image doesn’t bother too much with text space. So the right side would be trimmed as the width gets narrower.
 
 Other things
 -  Please add the link to the risk warning. `https://docs.algem.io/algem-protocol/risk-management`
 - Sorry but  please show the underbar as default (mobile users would not see it otherwise)

2022-07-25 07:31 UTC, sirius651 commented
> @sirius651
> 
> Thanks but I wanted to make the image fix on the left so the graphic image doesn’t bother too much with text space. So the right side would be trimmed as the width gets narrower. (please see this: https://algem-lending-dev.vercel.app/)
> 
> Other things
> 
> * Please add the link to the risk warning. `https://docs.algem.io/algem-protocol/risk-management`
> * Sorry but  please show the underbar as default (mobile users would not see it otherwise)

made a quick fix. regarding image, set position left from center. can you check again? @Kahonnohak

2022-07-25 07:33 UTC, Kahonnohak commented
Thank you look great! I'll ask Shun to review.

2022-10-07 04:27 UTC, sirius651 commented
@niklabh could you help why rpc-tests(shiden) is not successful?

2022-10-07 04:39 UTC, niklabh commented
fixed by rerun

2022-10-07 05:55 UTC, sirius651 commented
@Kahonnohak everything is on ready

2022-10-07 06:48 UTC, Kahonnohak approved these changes
Finally! LGTM!

2022-10-07 07:01 UTC, merged