Updating the French version of the Astar portal
AstarNetwork/astar-apps pull request #589
Opened 2022-11-19 09:31 UTC by Gunit2481

**Pull Request Summary**

> Describe what changes this pull request makes to the repository.

- Translation of the [Index.ts](https://github.com/AstarNetwork/astar-apps/blob/main/src/i18n/en-US/index.ts) file from the root `astar-apps/blob/main/src/i18n/en-US` into French
- Updating the [French Astar portal file](https://github.com/AstarNetwork/astar-apps/blob/main/src/i18n/fr/index.ts) from the root `astar-apps/blob/main/src/i18n/fr`
- Translation has been verified by the three french ambassadors

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**
- (ex: Add feature A)

**Fixes**
- (ex: Fix validation function)

**Changes**
- (ex: Change document B)

**To-dos**
> *Feel free to remove this section if it's not applicable

- [ ] (ex: add user list)

2022-11-20 00:56 UTC, 0xRamz approved these changes

2022-11-24 17:55 UTC, gluneau requested changes
There is still many iterations of Staking that should become "Jalonner" and the same for Unbonding as "Délier"

I will continue my review once those have been addressed.

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +  ticker: 'Ticker',
Téléscripteur

ex: https://www.cairn.info/revue-reseaux1-2003-6-page-137.htm#pa2

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
>      dappStaking: 'dApp Staking',
Jalonnement dApps

ex: https://kriptomat.io/fr/crypto-monnaies/quest-ce-que-le-jalonnement-de-crypto-monnaies/

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    staking: 'Staking',
Jalonner

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    endpoint: 'Endpoint',
Point de terminaison

ex: https://m.interglot.com/en/fr/endpoint

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    build2earn: 'Build2Earn',
Construire pour gagner

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    totalDapps: 'Total dApps'
dApps au total

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    index: 'Index',
Indice

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    stakedAmount: "Montant staké",
Montant jalonné

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    rebondGuide: "Une fois que vos fonds seront reliés en staking, vous aurez besoin de 10era pour les libérer à nouveau.",
Une fois que vos fonds seront en jalonnement, vous aurez besoin de 10 ères pour les libérer à nouveau.

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    unbond: 'Unbond',
Délier

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    unbondingAmount: "Montant d'unbonding",
Montant à délier

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    totalStaked: "Total Staké",
Total jalonné

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    restakeTip: "En activant, vos récompenses seront automatiquement remises en staking lorsque vous ferez une réclamation."
En activant, vos récompenses seront automatiquement remises en alonnement lorsque vous ferez une réclamation.

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    myStaking: "Mon Staking",
Mon jalonnement

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    unbonding: 'Unbonding',
Délier

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
>      dappStaking: 'dApp Staking',
Jalonnement dApp

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
>      dappsStore: 'dApps Store',
Boutique dApps

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    unbond: 'Unbond',
Délier

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    stake: 'Stake',
Jalonner

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
>      claim: 'Claim',
Réclamer

2022-11-24 17:55 UTC, gluneau commented on src/i18n/fr/index.ts
> +    stakersCount: "Stakers :",
Jalonneur :

2022-11-30 13:16 UTC, impelcrypto commented
Hi, I've updated i18n files in [this](https://github.com/AstarNetwork/astar-apps/pull/608) PR. Please take a look at these 2 files and update the French file accordingly. Thanks!

https://github.com/AstarNetwork/astar-apps/blob/main/src/i18n/en-US/index.ts
https://github.com/AstarNetwork/astar-apps/blob/main/src/i18n/fr/index.ts

2022-12-01 08:50 UTC, GuiGou12358 commented on src/i18n/fr/index.ts
> +    stakedAmount: "Montant staké",
Hello @gluneau
Je pense qu'il est préférable de garder certains termes anglais. En crypto, je pense que personne ne connais le terme jalonner ou jalonnement. Pour cette raison il est préférable de conserver le terme "staking".

2022-12-01 08:52 UTC, GuiGou12358 approved these changes

2022-12-01 09:00 UTC, GuiGou12358 approved these changes

2023-02-20 07:11 UTC, impelcrypto commented
@gluneau I think we can close this PR since PR #694 has been merged.

2023-02-24 09:38 UTC, Gunit2481 commented
Since a French translation has been added to the portal in a different way, I close this PR.

Please refer to PR #698 for all matters related to the French version of the portal.

2023-02-24 09:38 UTC, closed without merging