Fix styling for the dApp Staking top page hero area on mobile
AstarNetwork/astar-apps pull request #612
Opened 2022-12-01 04:11 UTC by sirius651

**Pull Request Summary**

> Fix styling for the dApp Staking top page hero area on mobile

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

2022-12-01 04:14 UTC, sirius651 commented
@Kahonnohak I've fixed the css on mobile view. could you check if it's modified as expected?

2022-12-01 09:37 UTC, Kahonnohak commented
Thanks!

I forgot to share the Figma link : https://www.figma.com/file/oXRfGoOgf6Yp84wJhwdvRg/dApp-Staking-V2-Kaizen?node-id=606%3A13980&t=MEp4o5ZmFrdN7D90-1

Let's make it clear one by one

1: The space here, is the same as before: if line brakes then the total height will change but the padding stay the same.
2: Can we remove this padding please and let people know that the contents extend?
3: The bottom padding is also same as before. My suggestion was to align at the bottom but we can have a look at it when the top align like you did now.
4: Could you give it a little more line space here please? It looks like there are two blocks so I cannot say the line height but maybe to have space of about 6px?

I hope it makes sense and ping me if anything is not clear.

2022-12-01 12:24 UTC, sirius651 commented
![스크린샷 2022-12-01 오후 9 22 52](https://user-images.githubusercontent.com/1606820/205051961-f467429e-8f1a-403c-b7d9-d7486cb48db9.png)

@Kahonnohak  fixed as you suggested. could you check again?

2022-12-01 13:58 UTC, Kahonnohak commented
Hi thank you lets sync tomorrow when I wake up!

- I did not want to change the title location but wanted to use more space towards the bottom - I thought we might still have the image above but let me know if that is the issue
- Could you please remove the side space and show the contents till the edge (right side) 

<img width="897" alt="スクリーンショット 2022-12-01 13 50 51" src="https://user-images.githubusercontent.com/77480847/205070800-020364cf-5109-4c52-8513-afeec538dc5a.png">

Does it make sense?

2022-12-02 06:19 UTC, sirius651 commented
> Does it make sense?

I fixed as you suggested. please check and if there's something let's sync

2022-12-02 10:27 UTC, sirius651 commented
@Kahonnohak I believe fixed it on feedback. please check

2022-12-02 13:57 UTC, Kahonnohak commented
Lovely!! Thank you!

Last request. 
- Could you make the width even for each box? (at the moment each box has different width)
- It would be good if you could break the line for the Era as well? 

<img width="934" alt="スクリーンショット 2022-12-02 13 55 50" src="https://user-images.githubusercontent.com/77480847/205308993-e5b8f0c7-6973-41d7-ae56-313c69eb6fc3.png">
<img width="937" alt="スクリーンショット 2022-12-02 13 56 18" src="https://user-images.githubusercontent.com/77480847/205309000-be3d244c-c2d7-43c7-a166-aef46d2c7d79.png">

Getting there!

2022-12-03 12:26 UTC, sirius651 commented
> Getting there!

Fixed in this [PR](https://github.com/AstarNetwork/astar-apps/pull/612/commits/b22201d3e474d169e69ace6b494bc48aa4948764)

2022-12-04 18:10 UTC, Kahonnohak approved these changes
It looks awesome thank you so much!

2022-12-06 05:36 UTC, impelcrypto commented
@sirius651 @Kahonnohak 
Perhaps add a padding or make font size slightly smaller here (only when the browser width is 375px)?

![image](https://user-images.githubusercontent.com/92044428/205825204-d77ff8cd-0a76-461f-9fdf-38c0544cdb67.png)

2022-12-06 05:41 UTC, impelcrypto commented
maybe like this?
![Screenshot 2022-12-06 at 1 39 41 PM](https://user-images.githubusercontent.com/92044428/205826094-c57bdcfa-b866-41ef-b5e8-770ee9db0438.png)

2022-12-06 05:43 UTC, Kahonnohak commented
Great!

2022-12-06 07:53 UTC, bobo-k2 approved these changes

2022-12-06 12:19 UTC, sirius651 commented
> maybe like this?

Fixed as you suggested

2022-12-06 13:32 UTC, impelcrypto requested changes
Could you use @media (max-width:) instead of max-width in this file? Other than that, LGTM!

2022-12-07 07:23 UTC, sirius651 commented on src/components/dapp-staking-v2/my-staking/styles/top-metric.scss
> +    @media (max-width: $sm) {
Fixed in [here](https://github.com/AstarNetwork/astar-apps/pull/612/commits/d7f9ef0ad6ad3a4ca97edf81f5ea2cdf3ee6b2e5)

2022-12-07 09:21 UTC, impelcrypto commented
@sirius651 It looks like my CLI is having an issue to fix the conflicts. Could you help resolve the conflicts and merge this PR? I think you can delete the 2 conflict files:

 src/components/dapp-staking-v2/my-staking/TopMetric.vue
src/components/dapp-staking-v2/my-staking/styles/top-metric.scss

2022-12-07 11:40 UTC, merged