Add theme :: Seasonal design - Luna New Year
AstarNetwork/astar-apps pull request #672
Opened 2023-01-18 11:26 UTC by sirius651

**Pull Request Summary**

Add theme :: Seasonal design - Luna New Year

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**Release notes:**
- feat: add theme :: Seasonal design - Luna New Year

![스크린샷 2023-01-18 오후 6 17 08](https://user-images.githubusercontent.com/1606820/213159706-81982854-6b23-44c2-a894-26033c028202.png)
![스크린샷 2023-01-18 오후 6 17 27](https://user-images.githubusercontent.com/1606820/213159719-82a90401-6917-49fe-ae8e-7ee3dd6934b0.png)

2023-01-18 12:31 UTC, bobo-k2 approved these changes
LGTM

2023-01-18 15:32 UTC, Kahonnohak requested changes

2023-01-18 15:32 UTC, Kahonnohak commented on src/components/common/themes/DividerNewYear.vue
> +  background: linear-gradient(180deg, #fdc605 0%, #793b02 100%);
Please change to 225deg, #d9802e, #793b02

2023-01-18 15:32 UTC, Kahonnohak commented on src/components/common/themes/DividerNewYear.vue
> +  text-shadow: 0px 1px 1px rgba(0, 0, 0, 0.5);
Please remove the text shadow

2023-01-18 15:34 UTC, Kahonnohak commented
Hi Thank you @sirius651 

I learned how I can request changes from the code...!

Apart from the colour and the fireworks, Gold line is on top of the wallet modal on Mobile. Please take a look.

<img width="418" alt="スクリーンショット 2023-01-18 14 13 26" src="https://user-images.githubusercontent.com/77480847/213214655-73c80f17-872c-4c3c-87ed-841a2e89278c.png">

Thanks

2023-01-19 02:38 UTC, sirius651 commented
> Thanks

@Kahonnohak Fixed above issues and adjust more about fireworks like making more smaller and set probability goes lower and increased more particles. please check again

2023-01-19 11:41 UTC, sirius651 commented
@Kahonnohak could you check again? I updated animation more by adjusting flag. but because of the size of canvas, it seems different :(

2023-01-19 11:49 UTC, Kahonnohak commented
@sirius651 Thanks I have looked but.. Shall we remove it? we would not have time to improve.

Another small thing I noticed now - when loading the logo appears late. If you can fix that would be good otherwise just remove the fireworks please.

2023-01-19 11:58 UTC, sirius651 commented
> Another small thing I noticed now - when loading the logo appears late. If you can fix that would be good otherwise just remove the fireworks please.

Fixed it

2023-01-19 13:06 UTC, Kahonnohak commented
Sorry...! If you have time, can you look into this? It is not good... (logo comes later than anything)
https://gyazo.com/89df545fc2dbb22e7c9d2dd3b2ba8414

2023-01-19 13:20 UTC, sirius651 commented
> Sorry...! If you have time, can you look into this? It is not good... (logo comes later than anything)
> https://gyazo.com/89df545fc2dbb22e7c9d2dd3b2ba8414

When I look at this, this is a problem currently in the portal, which seems slow because it needs to print the appropriate logo like astar, shiden according to networkInfo. Perhaps to solve this problem, the architecture needs to be fixed, so it would be better to work on a new PR.

2023-01-19 13:33 UTC, Kahonnohak commented
You are right okay, but so sorry I found other things - the logo size is small and the location is not good (not aligned )

Could you quickly change those below please.

- Padding above the logo to 24px
- The logo size to 112%


<img width="371" alt="スクリーンショット 2023-01-19 13 30 44" src="https://user-images.githubusercontent.com/77480847/213455723-d6a9d135-12c1-4943-881b-2fd66fae034d.png">

<img width="159" alt="スクリーンショット 2023-01-19 13 31 14" src="https://user-images.githubusercontent.com/77480847/213455729-679db6af-9c5d-47a8-a11d-54210eafe905.png">

2023-01-19 13:57 UTC, sirius651 commented
> You are right okay, but so sorry I found other things - the logo size is small and the location is not good (not aligned )
> 
> Could you quickly change those below please.
> 
> * Padding above the logo to 24px
> * The logo size to 112%
> 
it seems fixed now, can you check again?

2023-01-19 13:57 UTC, Kahonnohak commented
@sirius651 and rabbit on the top of the gold line - sorry keep adding in last minute. I did not know you have day off tomorrow.

2023-01-19 14:07 UTC, Kahonnohak commented
Yes thank you checked, and the location is a bit different from the current but if we can go back to the right place after the celebration period that is okay. 

- Shiden also need to change the logo size
- The previous post, the gold line should be behind the rabbit.

Hope you can make it...

thanks

2023-01-19 14:30 UTC, sirius651 commented
> thanks

Sorry for hurry, I believe it's fixed above?

2023-01-19 14:36 UTC, Kahonnohak commented
Thank you!!!!! Shiden looks good but Astar rabbits is under the golden line... Is it my cache?

2023-01-19 14:37 UTC, Kahonnohak commented
It was cache! All good thanks

2023-01-19 14:37 UTC, sirius651 commented
![스크린샷 2023-01-19 오후 11 36 57](https://user-images.githubusercontent.com/1606820/213470379-0b69aed8-3092-4e6b-813e-00c4025b6180.png)

I think so, he's on the gold line :)

2023-01-19 14:38 UTC, Kahonnohak approved these changes
Thanks!

2023-01-19 14:39 UTC, merged