Added dynamic links
AstarNetwork/astar-apps pull request #775
Opened 2023-05-08 13:03 UTC by niklabh

**Pull Request Summary**

> Describe what changes this pull request makes to the repository

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**Release notes:**

- (ex: feat: updated dApp staking to V2)
- (ex: fix: modified styling bugs on the Assets page)

**This pull request makes the following changes:**

**Adds**

- (ex: Add feature A)

**Fixes**

- (ex: Fix validation function)

**Changes**

- (ex: Change document B)

**To-dos**

> \*Feel free to remove this section if it's not applicable

- [ ] (ex: add user list)

2023-05-09 04:03 UTC, impelcrypto requested changes

2023-05-09 04:03 UTC, impelcrypto commented on src/components/assets/DynamicLinks.vue
> +      background: banners[item.background],
maybe use index instead of `item.background`?

2023-05-09 04:03 UTC, impelcrypto commented on src/data/dynamic_links.json
> +      "subtitle": "Portal is now on IPFS!",
Let's use i18n here

2023-05-09 04:03 UTC, impelcrypto commented on src/components/assets/DynamicLinks.vue
> +      title: item.title,
Let's use i18n in title and subtitle

2023-05-09 04:11 UTC, impelcrypto commented
@niklabh It's not responsive, and it breaks other UIs. Perhaps you can refer to dApp staking page  
![image](https://user-images.githubusercontent.com/92044428/236991290-bf1419eb-5136-4fab-aef2-6a99b838e44c.png)

![image](https://user-images.githubusercontent.com/92044428/236992008-048bd7dd-f288-451f-ba41-2311c2f8f437.png)

2023-05-09 05:55 UTC, bobo-k2 requested changes
The code LGTM, but please update Release notes section in the PR description

2023-05-09 12:59 UTC, Kahonnohak commented
Thanks @impelcrypto!!!

@gluneau Could you help @niklabh add the latest blog here, please?

2023-05-09 14:12 UTC, niklabh commented
> @niklabh It's not responsive, and it breaks other UIs. Perhaps you can refer to dApp staking page (scroll-able) ![image](https://user-images.githubusercontent.com/92044428/236991290-bf1419eb-5136-4fab-aef2-6a99b838e44c.png)
> 
> ![image](https://user-images.githubusercontent.com/92044428/236992008-048bd7dd-f288-451f-ba41-2311c2f8f437.png)

Fixed

2023-05-10 09:09 UTC, impelcrypto approved these changes

2023-05-10 10:21 UTC, Kahonnohak commented
Hi @niklabh 

Please check the ticket again, no need to trim the sides but only the top and bottom. And that should end up being able to scroll to the right, like dApp Staking. Could you also check that those banners would not be on the tooltip please?

<img width="382" alt="Screenshot 2023-05-10 at 11 12 19" src="https://github.com/AstarNetwork/astar-apps/assets/77480847/c352f368-2475-4bee-b5de-5543afa32053">

<img width="871" alt="Screenshot 2023-05-10 at 11 17 37" src="https://github.com/AstarNetwork/astar-apps/assets/77480847/48e5498b-0705-4d0a-929d-1bf45c279db2">
<img width="490" alt="Screenshot 2023-05-10 at 11 17 46" src="https://github.com/AstarNetwork/astar-apps/assets/77480847/f60b207a-b3cf-4682-b00a-86bdce657bd5">

2023-05-11 10:29 UTC, niklabh commented
> @niklabh Please do not merge this PR before the production page has been updated.

Link changed. Can this be merged now?

2023-05-11 10:56 UTC, Kahonnohak commented
No @niklabh the styling has not been fixed. Please see my last comment.

Also @gluneau please check, I could not get to the blog post.
https://gyazo.com/1d3bdfe49cba959c0733bf3a57a22da3

2023-05-11 11:00 UTC, niklabh commented
Hey @sirius651  can you please check the scrolling styling

2023-05-11 13:22 UTC, sirius651 commented
> Hey @sirius651 can you please check the scrolling styling

not sure exact output, but fixed as same as dapp staking card scrolling. please check @niklabh @Kahonnohak

2023-05-11 13:41 UTC, Kahonnohak commented
Thank you Will! Awesome!

Could I ask you
1) mobile to have no padding/margin on the right (same as dApp Staking)
2) Fix over-wrapping ads on the tooltip
3) Now desktop ads heights are now squashed, please take a look?

(this is not included in the release so no need to spend your evening for this)

<img width="725" alt="Screenshot 2023-05-11 at 14 29 10" src="https://github.com/AstarNetwork/astar-apps/assets/77480847/45d7633b-63f2-4c1c-b767-47d66fd80199">
<img width="369" alt="Screenshot 2023-05-11 at 14 33 38" src="https://github.com/AstarNetwork/astar-apps/assets/77480847/cb1dc4d0-eb8b-4bb8-a4e9-9f5be0dc41d0">


> > Hey @sirius651 can you please check the scrolling styling
> 
> not sure exact output, but fixed [here](https://github.com/AstarNetwork/astar-apps/pull/775/commits/19b814795e153865278f93ce5b78f688d92c36e7) as same as dapp staking card scrolling. please check @niklabh @Kahonnohak

2023-05-12 08:08 UTC, sirius651 commented
> Thank you Will! Awesome!
> 
> Could I ask you
> 
> 1. mobile to have no padding/margin on the right (same as dApp Staking)
> 2. Fix over-wrapping ads on the tooltip
> 3. Now desktop ads heights are now squashed, please take a look?
> 
> (this is not included in the release so no need to spend your evening for this)
> 

Fixed above [here](https://github.com/AstarNetwork/astar-apps/pull/775/commits/8fe65bdf94e4b92b745ca80ee1afc389e769e645) , please check again

2023-05-12 10:22 UTC, Kahonnohak commented
Thanks @sirius651 !

Could I ask you to make "Go Decentralized" in italic and weight 800? And styling is done! (for future, would it be simple to add animations to auto-scroll?)

@niklabh would you think "Portal is now on IPFS!" makes sense? Any better wording?

2023-05-12 12:30 UTC, sirius651 commented
> 

Updated as you suggested. I didn't catch the animations to auto-scroll. any reference for this?

2023-05-12 13:47 UTC, Kahonnohak commented
> > Thanks @sirius651 !
> > Could I ask you to make "Go Decentralized" in italic and weight 800? And styling is done! (for future, would it be simple to add animations to auto-scroll?)
> > @niklabh would you think "Portal is now on IPFS!" makes sense? Any better wording?
> 
> Updated as you suggested. I didn't catch the animations to auto-scroll. any reference for this?

Thank you! No worries for now. Styling done. Thanks for the help!

2023-05-17 13:52 UTC, Kahonnohak commented
Created a ticket for adding another banner on top of the header for the decentralised version, would you work on this or a new PR?

2023-05-18 14:12 UTC, impelcrypto commented
@Kahonnohak 

> Created a ticket for adding another banner on top of the header for the decentralised version, would you work on this or a new PR?

I'll create another PR for this

2023-05-19 08:59 UTC, impelcrypto commented on src/pages/AssetsPage.vue
> -  padding: 0 16px;
Could you advise why deleted here for mobile devices? @Kahonnohak @niklabh It makes the divider size longer.

<img width="462" alt="image" src="https://github.com/AstarNetwork/astar-apps/assets/92044428/1d2a733d-b570-4c86-9193-327c919b349e">

2023-05-19 09:08 UTC, impelcrypto commented on src/pages/AssetsPage.vue
> -  padding: 0 16px;
@sirius651

2023-05-19 09:09 UTC, impelcrypto commented on src/pages/AssetsPage.vue
> -  padding: 0 16px;
@sirius651  Could you fix it?

2023-05-19 09:13 UTC, impelcrypto commented on src/pages/AssetsPage.vue
> -  padding: 0 16px;
@sirius651 or you can fix it in [this](https://github.com/AstarNetwork/astar-apps/pull/803) PR.

2023-05-19 10:02 UTC, impelcrypto commented on src/pages/AssetsPage.vue
> -  padding: 0 16px;
@sirius651 I fixed in [this](https://github.com/AstarNetwork/astar-apps/pull/803/commits/486415b6caf7ecf2548f97d75bad837ac2b2ba47) commit.

2023-05-22 10:39 UTC, merged