fix: modified "claim rewards box" for dApp developer
AstarNetwork/astar-apps pull request #801
Opened 2023-05-18 09:47 UTC by impelcrypto

**Pull Request Summary**

* fix: modified "claim rewards box" for dApp developer

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Changes**

* fix: modified "claim rewards box" for dApp developer

If connected account is a 'dApp developer'
![image](https://github.com/AstarNetwork/astar-apps/assets/92044428/bb0b5875-f87e-4572-893a-d418325318f9)

If connected account is a 'Staker' (the UI is the same as current)
![image](https://github.com/AstarNetwork/astar-apps/assets/92044428/b81cd660-b7f5-455c-92f8-0d0861b0dc74)

2023-05-19 09:16 UTC, bobo-k2 commented
Please add a test case which covers changes made in this PR.

2023-05-19 09:25 UTC, niklabh approved these changes

2023-05-19 09:28 UTC, bobo-k2 requested changes
Add e2e test

2023-06-07 10:34 UTC, impelcrypto commented
@bobo-k2 
I've created test ID DS008 for this. I'll work on after we resolve the `forceNewEra` issue. Atm, I'd like to merge this PR first.

2023-06-07 10:53 UTC, bobo-k2 approved these changes

2023-06-07 10:53 UTC, merged