Add disclaimer dialog
AstarNetwork/astar-apps pull request #817
Opened 2023-05-31 08:13 UTC by sirius651

**Pull Request Summary**

Add disclaimer dialog

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

2023-06-01 14:19 UTC, bobo-k2 requested changes

2023-06-01 14:19 UTC, bobo-k2 commented on src/components/common/ModalDisclaimer.vue
> +      <div class="container--buttons">
I see dark border around buttons in light theme
<img width="606" alt="image" src="https://github.com/AstarNetwork/astar-apps/assets/8452361/9a5619ba-f33a-4e3d-9cff-7ac74ba86f2b">

2023-06-01 14:22 UTC, bobo-k2 commented on src/components/common/ModalDisclaimer.vue
> +export default defineComponent({
Add test(s) for the component

2023-06-01 16:27 UTC, Kahonnohak commented
Could we add a delay somehow? As it's quite "not inviting". It would be better to be able to see Portal and maybe a trigger to show the modal. Maybe when user scroll or click? What would you think?

2023-06-02 13:27 UTC, sirius651 commented
> Could we add a delay somehow? As it's quite "not inviting". It would be better to be able to see Portal and maybe a trigger to show the modal. Maybe when user scroll or click? What would you think?

Added delay about 2sec. please check and let me know if suitable

2023-06-02 14:27 UTC, Kahonnohak commented
Looks good! This won't be added to the next cycle since the disclaimer itself is being reviewed right now. I will update once its approved!

2023-06-05 09:01 UTC, impelcrypto requested changes

2023-06-19 07:41 UTC, impelcrypto approved these changes

2023-07-14 08:14 UTC, bobo-k2 approved these changes

2023-07-14 11:07 UTC, Kahonnohak commented
Hi, @bobo-k2 Please help when you have a spare time.

We need to add two links that we were waiting for.

**Terms of Service** (font weight 600 and Astar Blue)
https://docs.google.com/document/d/1gxM0PEzFq7nW5VB11pMcDUaaKxfMz3BjTDtmEem_oo4/edit#heading=h.hqbzr87xmci3

**Privacy Policy** (font weight 600 and Astar Blue)
https://docs.google.com/document/d/1jEbhRfh292TahRMRdeN4z-8MYNU27dCS_vVopV6xQgk/edit#heading=h.cey5hqakqpbb
<img width="729" alt="Screenshot 2023-07-14 at 12 05 53" src="https://github.com/AstarNetwork/astar-apps/assets/77480847/1dc8b783-29dd-4294-b895-9b12f3a10021">

2023-07-14 12:21 UTC, bobo-k2 requested changes
Add links

2023-08-08 16:57 UTC, Kahonnohak commented
We got proper links now! @gluneau could you please replace them?

Terms of Use
https://astar.network/term-of-use

Privacy policy
https://astar.network/privacy-policy

2023-08-09 09:38 UTC, Kahonnohak approved these changes
Thanks! Good to go!

2023-08-10 01:19 UTC, merged