Merge to main from release-hotfix
AstarNetwork/astar-apps pull request #832
Opened 2023-06-13 07:55 UTC by sirius651

**Pull Request Summary**

Merge to main from release-hotfix

2023-06-13 12:16 UTC, impelcrypto requested changes
There are old code exists in this branch.

2023-06-13 12:16 UTC, impelcrypto commented on tests/test_specs/dappstaking-transactions.spec.ts
> +  test('Twitter share button works', async ({ page, context }) => {
I've removed this line before

2023-06-13 12:34 UTC, impelcrypto requested changes

2023-06-16 08:24 UTC, Kahonnohak approved these changes

2023-06-16 08:26 UTC, merged